//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PjGara
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_bill
    {
        public int BiId { get; set; }
        public string BiCode { get; set; }
        public string BiType { get; set; }
        public string BiOName { get; set; }
        public Nullable<int> BiPrice { get; set; }
        public Nullable<int> BiQua { get; set; }
    }
}
