//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PjGara
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_cars
    {
        public int CarId { get; set; }
        public string CarCode { get; set; }
        public string CarName { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public string CarOwner { get; set; }
        public Nullable<System.DateTime> CarTime { get; set; }
    }
}
