//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PjGara
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_depot
    {
        public int DeId { get; set; }
        public string DeCode { get; set; }
        public string DeName { get; set; }
        public string DeModel { get; set; }
        public Nullable<int> DeQua { get; set; }
    }
}
