//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PjGara
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_employees
    {
        public int EmId { get; set; }
        public string EmCode { get; set; }
        public string EmName { get; set; }
        public Nullable<int> EmAge { get; set; }
        public string EmGender { get; set; }
        public string EmAddress { get; set; }
    }
}
