//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PjGara
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaraDataEntities1 : DbContext
    {
        public GaraDataEntities1()
            : base("name=GaraDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_bill> db_bill { get; set; }
        public virtual DbSet<db_cars> db_cars { get; set; }
        public virtual DbSet<db_depot> db_depot { get; set; }
        public virtual DbSet<db_employees> db_employees { get; set; }
    }
}
